### ISSUE TITLE
item texture

### ISSUE THREAD

**Issue by ekaj113** [pahimar/LetsModReboot#20]
my items textures arent showing up for me, i only have one github project but the paste bin for the log is http://pastebin.com/fs9XgWi3

**Comment by hidetzugu** [comment]
oh, crap... you just reminded me that I haven't touched mod code in... 2 mouths according to github.

Anyway, I had the same problem. You just need to switch your assets folder to lower-case, so main/resources/assets/mtmod instead of main/resources/assets/MTMod. Its just a convention used when MC is looking for your assets. It specifically "lower-cases" your mod name and looks for that. So you can keep your "code folder" as MTMod but the assets one need to be mtmod.

Cheers

**Comment by pahimar** [comment]
You should probably post bug reports for your project on your own projects page :-p

**Comment by ekaj113** [comment]
[redacted]

**Comment by pahimar** [comment]
Maybe you should keep the sass to yourself - the code here works fine. The issue is on your end @ekaj113.

**Comment by ekaj113** [comment]
sorry for the sass i have tried so many ways to fix it, and i could figure it out, do you know an easy fix for me or somebody who can help me, do you think it has something to do about how my mod is 0% groovy

**Comment by pahimar** [comment]
Your issue is just like how @hidetzugu explained it

Look here - https://github.com/ekaj113/More-Tools-Mod/blob/master/src/main/java/com/ekaj113/MTMod/item/ItemMTMod.java#L24

You tell Minecraft look for the texture here, and you set everything to lowercase

However, when you look here - https://github.com/ekaj113/More-Tools-Mod/tree/master/src/main/resources/assets

Your path to the texture is NOT all lowercase (see that its MTMod and not mtmod)

Minecraft is looking for mtmod, not MTMod, because you told it that's where to find it in your ItemMTMod class

Hopefully that helps.

**Comment by ghost** [comment]
Java is case sensitive. Just make sure your using those caps correctly ;)

**Comment by ekaj113** [comment]
when i did that it crashed the crash report is here http://pastebin.com/iniCn9ke

**Comment by Skyamoeba** [comment]
This is what's causing the crash as (correct me if I am wrong Pahimar / nmasa05 ) you need to make sure that your imports are the same as the class / package names so yours at the min is this

package com.ekaj113.MTMod.proxy;   <------ This line is what it's stating is wrong when I look at the log.

import com.ekaj113.MTMod.client.settings.Keybindings; <----- Could cause a problem in next load test
import com.ekaj113.MTMod.utility.LogHelper;     <----- Could cause a problem in next load test
import cpw.mods.fml.client.registry.ClientRegistry;
import net.minecraft.client.settings.KeyBinding;

Which (if I am reading this right) in turn is making this occur

Caused by: java.lang.NoClassDefFoundError: com/ekaj113/mtmod/proxy/ClientProxy (wrong name: com/ekaj113/MTMod/proxy/ClientProxy)

see how it's trying to load ...13/mtmod/proxy/Clie... but it's finding ..13/MTMod/proxy/Clie...

So what I would do is change the package name to match what it is looking for, stated in the first part of the ClientProxy class so it would now:

package com.ekaj113.mtmod.proxy;

And then see what it throws up when you do that it may through up another name error in a different package/ class depends what else needs the MTMod uppercase.

but when coding for me anyway the fun is breaking it and then finding the error, see it as a more complicated crossword puzzle.

Hope this was helpful / correct as I am learning at the min aswell and I remember having a similar issue.

At the time I was typing this I refreshed GitHub and saw that you are trying this, so did it work?
